GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Promises From The Ground Up",
    "author": "Joshw Comeau.",
    "url": "https://www.joshwcomeau.com/javascript/promises/",
    "likes": 57458
}

###
GET http://localhost:3003/