GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Regular Expression Metacharacters - What Does \\d Mean in RegEx?",
    "author": "Kolade Chris",
    "url": "https://www.freecodecamp.org/news/what-does-d-mean-in-regex/",
    "likes": 0
}

###
GET http://localhost:3003/