GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Functional State Update in React",
    "author": "Gakii",
    "url": "https://dev.to/gakii/functional-state-update-in-react-42io",
    "likes": 9
}

###
GET http://localhost:3003/